name: Node.js CI

on: [push]

jobs:
  crawling: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Docsearch Scraper
        uses: Embraser01/docsearch-scraper-action@0.0.1
        with:
          args: run ./docsearch.config.json
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_CRAWL_API_KEY }} 
