name: Node.js CI

on: [push]

jobs:
  crawling: 
    runs-on: [ubuntu-latest]
    steps:
      - name: DocSearch Scraper
        uses: docker://algolia/docsearch-scraper:v1.6.0
        with:
          args: ./docsearch.config.json
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_CRAWL_API_KEY }} 
