name: Node.js CI

on: [push]

jobs:
  crawling: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Docsearch Scraper
        uses: docker://algolia/docsearch-scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_CRAWL_API_KEY }}
