name: Node.js CI

on: [push]

jobs:
  crawling: 
    runs-on: [ubuntu-latest]
    container: algolia/docsearch-scraper
    steps:
      - name: Docsearch Scraper
        run: |
          cd /root
          pipenv run python -m src.index
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_CRAWL_API_KEY }}
