name: Node.js CI

on: [push]

jobs:
  crawling: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Docsearch Scraper
        run: docker help
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_CRAWL_API_KEY }}
          CONFIG: {"index_name":"CheatSheets","start_urls":[{"url":"https://pfongkye.github.io/","tags":["docs"]}],"sitemap_urls":["https://pfongkye.github.io/sitemap.xml"],"sitemap_alternate_links":true,"stop_urls":["/help","/users"],"selectors":{"lvl0":{"selector":".menu__link--sublist.menu__link--active","global":true,"default_value":"Documentation"},"lvl1":"header h1","lvl2":"article h2","lvl3":"article h3","lvl4":"article h4","lvl5":"article h5","lvl6":"article h6","text":"article p, article li"},"selectors_exclude":[".hash-link"]}
