name: Node.js CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: | 
        git config --global user.email "p.fongkye@users.noreply.github.com"
        git config --global user.name "p.fongkye"
        echo "machine github.com login p.fongkye password $GIT_PERSO_TOKEN" > ~/.netrc
        npm run deploy
      env:
        CI: true
        GIT_USER: p.fongkye
        GIT_PERSO_TOKEN: ${{ secrets.GIT_PERSO_TOKEN }}
    - uses: .github/actions/docsearch-crawl/action
    - name: Hello world action step
      id: hello
      with:
        who-to-greet: 'PFK'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
