name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: | 
        git config --global user.email "p.fongkye@users.noreply.github.com"
        git config --global user.name "p.fongkye"
        echo "machine github.com login p.fongkye password $GIT_PERSO_TOKEN" > ~/.netrc
        npm run deploy
      env:
        CI: true
        GIT_USER: p.fongkye
        GIT_PERSO_TOKEN: ${{ secret.GIT_PERSO_TOKEN }}
